'use client'

import { Download } from 'lucide-react'
import type { ValidationResult } from '@/lib/types'
import ScoreDisplay from './ScoreDisplay'
import VerdictBadge from './VerdictBadge'
import FrameworkCard from './FrameworkCard'

interface ResultsDisplayProps {
  result: ValidationResult
}

export default function ResultsDisplay({ result }: ResultsDisplayProps) {
  const downloadReport = () => {
    const report = `# 🏛️ STRATEGIC ASSESSMENT: ${result.idea.substring(0, 50)}...
**Metron Value Score:** \`${result.metronScore}/100\`

---

## 1. THE DEFENSE (Michael Porter)
**Framework:** Five Forces & Barriers to Entry
*   **Score:** ${result.porter.score}/100
*   **Strength:** ${result.porter.strength}
*   **Critical Weakness:** ${result.porter.weakness}
*   > "${result.porter.analysis}"

## 2. THE MOAT (Warren Buffett)
**Framework:** Durable Competitive Advantage & Pricing Power
*   **Score:** ${result.buffett.score}/100
*   **Strength:** ${result.buffett.strength}
*   **Critical Weakness:** ${result.buffett.weakness}
*   > "${result.buffett.analysis}"

## 3. THE ENGINE (Jim Collins)
**Framework:** The Flywheel & Hedgehog Concept
*   **Score:** ${result.collins.score}/100
*   **Strength:** ${result.collins.strength}
*   **Critical Weakness:** ${result.collins.weakness}
*   > "${result.collins.analysis}"

---

## ⚖️ THE METRON VERDICT
**CONCLUSION: ${result.verdict}.** ${result.verdictMessage}

---
*Generated by Value Validator | Metron Ventures*
`

    const blob = new Blob([report], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `Strategic_Assessment_${Date.now()}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-8 animate-fade-in">
      <ScoreDisplay score={result.metronScore} />

      <div className="grid md:grid-cols-3 gap-6">
        <FrameworkCard
          title="The Defense"
          subtitle="Michael Porter"
          score={result.porter.score}
          strength={result.porter.strength}
          weakness={result.porter.weakness}
          analysis={result.porter.analysis}
          icon="🛡️"
        />
        <FrameworkCard
          title="The Moat"
          subtitle="Warren Buffett"
          score={result.buffett.score}
          strength={result.buffett.strength}
          weakness={result.buffett.weakness}
          analysis={result.buffett.analysis}
          icon="🏰"
        />
        <FrameworkCard
          title="The Engine"
          subtitle="Jim Collins"
          score={result.collins.score}
          strength={result.collins.strength}
          weakness={result.collins.weakness}
          analysis={result.collins.analysis}
          icon="⚙️"
        />
      </div>

      <VerdictBadge verdict={result.verdict} message={result.verdictMessage} />

      <button
        onClick={downloadReport}
        className="w-full md:w-auto px-8 py-3 bg-navy-700 hover:bg-navy-600 border border-navy-600 rounded-lg text-white font-medium transition-colors flex items-center justify-center gap-2"
      >
        <Download size={20} />
        Download Strategic Assessment Report
      </button>
    </div>
  )
}

